Removed dead code causing compilation errors on Ubuntu 16.10
The function lomax calls isnan with a long.
This causes the compilation to fail on ubuntu 16.10 with
gcc version 6.2.0-5ubuntu12 and glibc version 2.24-3ubuntu1.
The function is never called, so I simply removed it.

Error message:
util.c: In function ‘lomax’:
util.c:264:9: error: non-floating-point argument in call to function ‘__builtin_isnan’
         if(x[i]>th && isnan(x[i])==0 && isinf(x[i])==0){
         ^~
util.c:264:9: error: non-floating-point argument in call to function ‘__builtin_isinf_sign’
Makefile:23: recipe for target 'util.o' failed
make: *** [util.o] Error 1